"""LLM-backed exploration actors for the Inspector-Reviewer-Coder-Debugger loop.

The actors keep LangChain dependencies at the boundary: Inspector uses plain
chat invocation for planning, Reviewer uses structured output, and
Coder/Debugger make notebook changes only through bound tools.
"""

from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Protocol, TypeVar, cast

from langchain.agents import create_agent
from langchain.messages import AIMessage, AnyMessage, HumanMessage, SystemMessage
from langchain_core.tools import StructuredTool

from statigent.errors import StatigentExplorationError
from statigent.exploration.prompts import (
    CODER_SYSTEM_PROMPT,
    DEBUGGER_SYSTEM_PROMPT,
    FINAL_DRAFT_SYSTEM_PROMPT,
    FINAL_REVIEWER_SYSTEM_PROMPT,
    INSPECTOR_PLAN_SYSTEM_PROMPT,
    REVIEWER_PLAN_SYSTEM_PROMPT,
)
from statigent.exploration.tools import make_record_debug_lesson_tool
from statigent.notebook.base import NotebookKernel
from statigent.retry import (
    extract_usage_metadata,
    invoke_structured_with_retries,
    invoke_structured_with_usage,
    retry_on_parse_error,
)
from statigent.schemas import (
    DatasetProfile,
    DebugDecision,
    DebugLesson,
    ExplorationStep,
    FinalDraft,
    FinalReviewDecision,
    NotebookCell,
    NotebookCellResult,
    ReviewerPlanDecision,
    TaskBrief,
)

if TYPE_CHECKING:
    from langchain_core.language_models.chat_models import BaseChatModel

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)


@dataclass(frozen=True)
class ToolCallOutcome:
    """Result of a tool-call model invocation with token usage."""

    result: object
    usage_metadata: dict[str, int]


@dataclass(frozen=True)
class CoderExecutionOutcome:
    """Notebook cell generated by Coder and its immediate execution result."""

    cell: NotebookCell
    result: NotebookCellResult
    observation: str


@dataclass(frozen=True)
class DebugExecutionOutcome:
    """Debugger replacement outcome with the validation execution result."""

    cell: NotebookCell
    result: NotebookCellResult
    lessons: list[DebugLesson]


class _StructuredRunnable(Protocol[T_co]):
    def invoke(self, messages: list[AnyMessage]) -> T_co: ...


class _StructuredModel(Protocol):
    def with_structured_output(
        self, schema: type[T], *, include_raw: bool = False
    ) -> _StructuredRunnable[Any]: ...


class _ChatModel(_StructuredModel, Protocol):
    def invoke(self, messages: list[AnyMessage]) -> object: ...


class _ToolRunnable(Protocol):
    def invoke(self, messages: list[AnyMessage]) -> object: ...


class _ToolModel(Protocol):
    def bind_tools(self, tools: list[StructuredTool]) -> _ToolRunnable: ...


class _AgentRunnable(Protocol):
    def invoke(self, inputs: dict[str, object]) -> object: ...


AgentFactory = Callable[[object, list[StructuredTool], str], _AgentRunnable]


def _create_agent(
    model: object,
    tools: list[StructuredTool],
    system_prompt: str,
) -> _AgentRunnable:
    return cast(
        "_AgentRunnable",
        create_agent(cast("BaseChatModel", model), tools, system_prompt=system_prompt),
    )


def _invoke_with_retries[T](
    model: _StructuredModel,
    schema: type[T],
    messages: list[AnyMessage],
) -> T:
    structured = model.with_structured_output(schema, include_raw=True)
    result = retry_on_parse_error(invoke_structured_with_retries)(structured, messages)
    return cast("T", result)


def _invoke_with_usage[T](
    model: _StructuredModel,
    schema: type[T],
    messages: list[AnyMessage],
) -> tuple[T, dict[str, int]]:
    structured = model.with_structured_output(schema, include_raw=True)
    result, usage_metadata = retry_on_parse_error(invoke_structured_with_usage)(
        structured, messages
    )
    return cast("T", result), usage_metadata


def _message_text(result: object) -> str:
    if isinstance(result, str):
        return result
    if isinstance(result, AIMessage):
        if isinstance(result.content, str):
            return result.content
        return str(result.content)
    content = getattr(result, "content", None)
    if isinstance(content, str):
        return content
    return str(result)


def _agent_response_text(result: object) -> str:
    if isinstance(result, dict):
        messages = result.get("messages")
        if isinstance(messages, list) and messages:
            return _message_text(messages[-1])
    return _message_text(result)


def _agent_usage_metadata(result: object) -> dict[str, int]:
    if isinstance(result, dict):
        messages = result.get("messages")
        if isinstance(messages, list) and messages:
            return extract_usage_metadata(messages[-1])
    return extract_usage_metadata(result)


def _invoke_tool_call(
    model: _ToolModel,
    tools: list[StructuredTool],
    messages: list[AnyMessage],
    expected_tool_name: str,
    *,
    invoke_additional_tools: bool = False,
) -> ToolCallOutcome:
    response = model.bind_tools(tools).invoke(messages)
    return _handle_tool_call_response(
        response,
        tools,
        expected_tool_name,
        invoke_additional_tools=invoke_additional_tools,
    )


def _invoke_bound_tool_call(
    model: _ToolRunnable,
    tools: list[StructuredTool],
    messages: list[AnyMessage],
    expected_tool_name: str,
) -> ToolCallOutcome:
    response = model.invoke(messages)
    return _handle_tool_call_response(response, tools, expected_tool_name)


def _handle_tool_call_response(
    response: object,
    tools: list[StructuredTool],
    expected_tool_name: str,
    *,
    invoke_additional_tools: bool = False,
) -> ToolCallOutcome:
    if not isinstance(response, AIMessage):
        raise StatigentExplorationError(
            f"Tool model returned {type(response).__name__}, expected AIMessage"
        )
    tool_by_name = {tool.name: tool for tool in tools}
    expected_calls = []
    for call in response.tool_calls:
        name = call["name"]
        if name not in tool_by_name:
            raise StatigentExplorationError(f"Unknown tool call: {name}")
        if name == expected_tool_name:
            expected_calls.append(call)
    if len(expected_calls) != 1:
        raise StatigentExplorationError(
            f"Model must call exactly one {expected_tool_name}; "
            f"received {len(expected_calls)}"
        )
    seen_tool_names: set[str] = set()
    for call in response.tool_calls:
        name = call["name"]
        if name in seen_tool_names:
            raise StatigentExplorationError(f"Duplicate tool call: {name}")
        seen_tool_names.add(name)
    expected_result: object | None = None
    if invoke_additional_tools:
        for call in response.tool_calls:
            name = call["name"]
            result = tool_by_name[name].invoke(call["args"])
            if name == expected_tool_name:
                expected_result = result
        return ToolCallOutcome(
            result=expected_result,
            usage_metadata=extract_usage_metadata(response),
        )
    return ToolCallOutcome(
        result=tool_by_name[expected_tool_name].invoke(expected_calls[0]["args"]),
        usage_metadata=extract_usage_metadata(response),
    )


class Inspector:
    """Proposes the next exploration action and drafts the final output."""

    def __init__(self, model: object) -> None:
        self.model = cast("_ChatModel", model)
        self.last_usage_metadata: dict[str, int] = {}

    def next_plan(
        self,
        brief: TaskBrief,
        profile: DatasetProfile,
        steps: list[ExplorationStep],
        reviewer_feedback: str,
    ) -> str:
        """Return an unstructured text plan for the next exploration step."""
        result = self.model.invoke(
            [
                SystemMessage(content=INSPECTOR_PLAN_SYSTEM_PROMPT),
                HumanMessage(
                    content=(
                        f"Task brief:\n{brief.model_dump_json()}\n\n"
                        f"Profile:\n{profile.compact_summary()}\n\n"
                        f"Completed steps:\n{[s.model_dump() for s in steps]}\n\n"
                        f"Reviewer feedback:\n{reviewer_feedback}"
                    ),
                ),
            ]
        )
        self.last_usage_metadata = extract_usage_metadata(result)
        return _message_text(result)

    def final_draft(
        self,
        brief: TaskBrief,
        profile: DatasetProfile,
        steps: list[ExplorationStep],
    ) -> FinalDraft:
        # TODO: Output different types based on the task type. If it is only a data
        # analysis task (question-based), output the answer directly. If it is a data
        # modeling task, output a structured data insight report.
        result, self.last_usage_metadata = _invoke_with_usage(
            self.model,
            FinalDraft,
            [
                SystemMessage(content=FINAL_DRAFT_SYSTEM_PROMPT),
                HumanMessage(
                    content=(
                        f"Task brief:\n{brief.model_dump_json()}\n\n"
                        f"Profile:\n{profile.compact_summary()}\n\n"
                        # TODO: trim large step outputs before sending to LLM;
                        # full model_dump() may exceed context window limits.
                        f"Exploration steps:\n{[s.model_dump() for s in steps]}"
                    ),
                ),
            ],
        )
        return result


class Reviewer:
    """Reviews proposed actions for relevance and safety, and evaluates final drafts."""

    def __init__(self, model: object) -> None:
        self.model = cast("_StructuredModel", model)
        self.last_usage_metadata: dict[str, int] = {}

    def review_plan(
        self,
        brief: TaskBrief,
        profile: DatasetProfile,
        steps: list[ExplorationStep],
        plan_text: str,
    ) -> ReviewerPlanDecision:
        """Review an Inspector text plan as structured output."""
        result, self.last_usage_metadata = _invoke_with_usage(
            self.model,
            ReviewerPlanDecision,
            [
                SystemMessage(content=REVIEWER_PLAN_SYSTEM_PROMPT),
                HumanMessage(
                    content=(
                        f"Task brief:\n{brief.model_dump_json()}\n\n"
                        f"Dataset profile:\n{profile.compact_summary()}\n\n"
                        f"Full execution path:\n{[s.model_dump() for s in steps]}\n\n"
                        f"Inspector plan:\n{plan_text}"
                    ),
                ),
            ],
        )
        return result

    def review_final(
        self,
        brief: TaskBrief,
        steps: list[ExplorationStep],
        draft: FinalDraft,
    ) -> FinalReviewDecision:
        # TODO: The final review should be used to determine whether the insector's
        # final output has completed the tasks for this stage. If not, and if the budget
        # limit has not been reached, more exploration steps are needed.
        result, self.last_usage_metadata = _invoke_with_usage(
            self.model,
            FinalReviewDecision,
            [
                SystemMessage(content=FINAL_REVIEWER_SYSTEM_PROMPT),
                HumanMessage(
                    content=(
                        f"Task brief:\n{brief.model_dump_json()}\n\n"
                        f"Full execution path:\n{[s.model_dump() for s in steps]}\n\n"
                        f"Draft:\n{draft.model_dump_json()}"
                    ),
                ),
            ],
        )
        return result


class Coder:
    """Writes incremental Python notebook cells for approved exploration actions."""

    def __init__(
        self,
        model: object,
        kernel: NotebookKernel,
        *,
        agent_factory: AgentFactory = _create_agent,
    ) -> None:
        self.kernel = kernel
        self._last_outcome: CoderExecutionOutcome | None = None
        self._agent = agent_factory(
            model,
            [self._make_append_and_execute_tool()],
            CODER_SYSTEM_PROMPT,
        )
        self.last_usage_metadata: dict[str, int] = {}

    def _make_append_and_execute_tool(self) -> StructuredTool:
        def append_code_cell(
            code: str,
            purpose: str,
            expected_observation: str,
        ) -> str:
            """Append a notebook cell, execute it, and return the execution result."""
            cell = self.kernel.append_code_cell(
                code,
                purpose,
                expected_observation,
            )
            result = self.kernel.execute_cell(cell.cell_id)
            self._last_outcome = CoderExecutionOutcome(
                cell=cell,
                result=result,
                observation="",
            )
            return self._execution_result_text(result)

        return StructuredTool.from_function(append_code_cell)

    def append_and_execute(
        self,
        profile: DatasetProfile,
        instruction: str,
    ) -> CoderExecutionOutcome:
        """Append an approved code cell, execute it, and summarize the result."""
        input_paths = "\n".join(f"- {path}" for path in self.kernel.list_inputs())
        if not input_paths:
            input_paths = "- No input files are available."
        code_context = self.kernel.get_code_context().model_dump_json()
        self._last_outcome = None
        agent_result = self._agent.invoke(
            {
                "messages": [
                    HumanMessage(
                        content=(
                            f"Dataset profile:\n{profile.compact_summary()}\n\n"
                            f"Available input paths:\n{input_paths}\n\n"
                            f"Notebook code context:\n{code_context}\n\n"
                            "Use the listed input paths exactly when reading data. "
                            "Do not invent filenames, directories, or mount points."
                            "\n\n"
                            f"Coder instruction:\n{instruction}"
                        ),
                    )
                ]
            }
        )
        self.last_usage_metadata = _agent_usage_metadata(agent_result)
        if self._last_outcome is None:
            raise StatigentExplorationError(
                "Coder agent did not call append_code_cell."
            )
        return CoderExecutionOutcome(
            cell=self._last_outcome.cell,
            result=self._last_outcome.result,
            observation=_agent_response_text(agent_result),
        )

    def append_code_cell(
        self,
        profile: DatasetProfile,
        instruction: str,
    ) -> NotebookCell:
        """Append an approved code cell without executing it."""
        return self.append_and_execute(profile, instruction).cell

    @classmethod
    def observation_for_result(
        cls,
        instruction: str,
        cell: NotebookCell,
        result: NotebookCellResult,
    ) -> str:
        """Create the Coder observation passed back to the Inspector."""
        status = "succeeded" if result.ok else "failed"
        return (
            f"Instruction: {instruction}\n"
            f"Cell: {cell.cell_id}\n"
            f"Execution {status}.\n"
            f"Observation:\n{cls._result_output(result)}"
        )

    @staticmethod
    def _result_output(result: NotebookCellResult) -> str:
        return result.stdout if result.ok else result.error_summary or result.stderr

    @classmethod
    def _execution_result_text(cls, result: NotebookCellResult) -> str:
        return (
            "Execution result:\n"
            f"cell_id: {result.cell_id}\n"
            f"ok: {result.ok}\n"
            f"exit_code: {result.exit_code}\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}\n"
            f"error_summary:\n{result.error_summary}"
        )

# TODO: The debugger should be equipped with a replace_code_cell tool, using a React
# agent focused on solving code debugging issues.
class Debugger:
    """Diagnoses failed cells and proposes corrected code, or recommends abandonment."""

    def __init__(
        self,
        model: object,
        *,
        agent_factory: AgentFactory = _create_agent,
    ) -> None:
        self.model = cast("_StructuredModel", model)
        self._tool_model = cast("_ToolModel", model)
        self._agent_factory = agent_factory
        self.last_usage_metadata: dict[str, int] = {}

    def debug_cell(
        self,
        brief: TaskBrief,
        kernel: NotebookKernel,
        failed_cell: NotebookCell,
        error: str,
        lessons: list[DebugLesson],
    ) -> DebugExecutionOutcome:
        """Repair a failed notebook cell and execute it to validate the fix."""
        last_replacement: DebugExecutionOutcome | None = None

        def replace_code_cell(
            code: str,
            purpose: str,
            expected_observation: str,
        ) -> str:
            """Replace the failed notebook cell and return the execution result."""
            nonlocal last_replacement
            cell = kernel.replace_code_cell(
                failed_cell.cell_id,
                code,
                purpose,
                expected_observation,
            )
            result = kernel.execute_cell(cell.cell_id)
            last_replacement = DebugExecutionOutcome(
                cell=cell,
                result=result,
                lessons=list(lessons),
            )
            return Coder._execution_result_text(result)

        replace_tool = StructuredTool.from_function(replace_code_cell)
        lesson_tool = make_record_debug_lesson_tool(lessons)
        agent = self._agent_factory(
            self._tool_model,
            [replace_tool, lesson_tool],
            DEBUGGER_SYSTEM_PROMPT,
        )
        agent_result = agent.invoke(
            {
                "messages": [
                    HumanMessage(
                        content=(
                            f"Task brief:\n{brief.model_dump_json()}\n\n"
                            f"Failed cell:\n{failed_cell.model_dump_json()}\n\n"
                            f"Error:\n{error}\n\n"
                            "Existing lessons:\n"
                            f"{[lesson.model_dump() for lesson in lessons]}"
                        ),
                    )
                ]
            }
        )
        self.last_usage_metadata = _agent_usage_metadata(agent_result)
        if last_replacement is None:
            raise StatigentExplorationError(
                "Debugger agent did not call replace_code_cell."
            )
        return DebugExecutionOutcome(
            cell=last_replacement.cell,
            result=last_replacement.result,
            lessons=list(lessons),
        )

    def debug(self, brief: TaskBrief, code: str, error: str) -> DebugDecision:
        return _invoke_with_retries(
            self.model,
            DebugDecision,
            [
                SystemMessage(
                    content=(
                        "You are the Debugger. Return corrected code if retrying "
                        "is useful; otherwise explain why to abandon this action."
                    ),
                ),
                HumanMessage(
                    content=(
                        f"Task brief:\n{brief.model_dump_json()}\n\n"
                        f"Failed code:\n{code}\n\nError:\n{error}"
                    ),
                ),
            ],
        )
