[deepseek-v4-flash]
model = "deepseek-v4-flash"
model_provider = "deepseek"
extra_body = {thinking = {type = "disabled"}}

[deepseek-v4-flash-thinking]
model = "deepseek-v4-flash"
model_provider = "deepseek"
reasoning_effort = "high"
extra_body = {thinking = {type = "enabled"}}
